<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Class AnswersTableSeeder
 * @author Hesham Mohamed <hesham.mohamed19930@gmail.com>
 */
class AnswersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('answers')->truncate();
        DB::table('answers')->insert([
            [
                'question_id' => 1,
                'answer_en' => 'Letters, Words, Colors, Shapes, Combinations',
                'answer_ar' => null,
                'answer_zh' => null,
                'answer_tr' => null,
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work can be protected as a trademark.
                 Trademarks can be words, phrases, logos, colors, or symbols, or a combination of those,
                 which represent a company’s brand is used on its products or services. Trademarks distinguish
                 the products or services of one company from another. Watch out, a trademark can’t be generic,
                 descriptive, offensive, misleading, or similar to a famous or existing mark.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 1,
                'answer_en' => 'An Invention',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '2',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 1,
                'answer_en' => 'A Secret Process',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '11',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 1,
                'answer_en' => 'A Design',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '12',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 1,
                'answer_en' => 'An Artistic Expression',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '5',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 1,
                'answer_en' => 'An Idea',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Unfortunately, there is no effective way to protect mere ideas with any
                form of intellectual property protection, although copyright law may protect the way these things are
                expressed. Ideas need to be expressed in a form that fits in the several types of IP. If your idea fits
                in any of the options listed in Question 1, we advise retaking the quiz. Otherwise, we advise contacting
                our team of experts to assist you and shed light on the matter.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 2,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your computer software’s code can be protected under copyright law.
                However if there are novel elements relating to the software which may be protected under patent law
                in some countries. We advise contacting our team of experts to assist you in finding out what aspects
                of your work can be protected and under which laws. <a class="colored-identity" href="./contact-us">Contact Us</a> if you wish to learn whether your software can be protected as a patent.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 2,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '3',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 3,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Sorry, None of the above can be protected and monopolized by one entity.
                They are openly available to the public.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 3,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '4',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 4,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work can be protected under patent law. To be patentable,
                the invention must be novel (new), useful, and non obvious. Certain requirements, such as novelty
                and non-obviousness, will require you to conduct a preliminary prior art search. It is advised to
                hire an attorney or agent to search comprehensively and determine whether your work is patentable.
                <a class="colored-identity" href="./contact-us">Contact Us</a> if you wish to learn how to protect your patent.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 4,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '1',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 5,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work is protected under copyright law. <a class="colored-identity" href="./contact-us">Contact Us</a>
                    if you wish to register your copyright. But in general, according to the Berne convention copyrights are protected the moment they are published.
                     Press this <a class="colored-identity" target="_blank" href="https://www.wipo.int/treaties/en/ip/berne/summary_berne.html">Link</a>',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 5,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '6',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 6,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your computer software’s code can be protected under copyright law,
                while any new invention related to your software may be protected under patent law in some countries.
                We advise contacting our team of experts to assist you in finding out what aspects of your work can be
                protected and under which laws',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 6,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '7',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 7,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '8',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 7,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '9',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 8,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work is protected under Industrial design law.
                <a class="colored-identity" href="./contact-us">Contact Us</a> if you wish to learn how to protect your industrial designs.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 8,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work is protected under copyright law. <a class="colored-identity" href="./contact-us">Contact Us</a>
                    if you wish to register your copyright. But in general, according to the Berne convention copyrights are protected the moment they are published.
                     Press this <a class="colored-identity" target="_blank" href="https://www.wipo.int/treaties/en/ip/berne/summary_berne.html">Link</a>',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 9,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work is protected under copyright law. <a class="colored-identity" href="./contact-us">Contact Us</a>
                    if you wish to register your copyright. But in general, according to the Berne convention copyrights are protected the moment they are published.
                     Press this <a class="colored-identity" target="_blank" href="https://www.wipo.int/treaties/en/ip/berne/summary_berne.html">Link</a>',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 9,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '10',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 10,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Unfortunately, there is no effective way to protect mere ideas with any form
                 of intellectual property protection, although copyright law may protect the way these things are
                 expressed. Ideas need to be expressed in a form that fits in the several types of IP. If your idea
                 fits in any of the options listed in Question 1, we advise retaking the quiz. Otherwise,we advise
                 contacting our team of experts to assist you and shed light on the matter',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 10,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '1',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 11,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work can be considered a Trade Secret. Trade secrets are protected by being
                a secret and not getting disclosed to the public. Make sure you have procedures in place to protect your trade secret.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 11,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '1',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 12,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work is protected under copyright law. <a class="colored-identity" href="./contact-us">Contact Us</a>
                    if you wish to register your copyright. But in general, according to the Berne convention copyrights are protected the moment they are published.
                     Press this <a class="colored-identity" target="_blank" href="https://www.wipo.int/treaties/en/ip/berne/summary_berne.html">Link</a>',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 12,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '13',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 13,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work can be protected under both industrial design and copyright laws.
                Seeking design protection though for those works provides better protection.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 13,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '14',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 14,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'Your work is protected under Industrial Design law.
                <a class="colored-identity" href="./contact-us">Contact Us</a> if you wish to learn how to protect your industrial designs.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 14,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 0,
                'next_question_ids' => '1',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 15,
                'answer_en' => 'You',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 1,
                'min_points' => 0,
                'next_question_ids' => '16',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 15,
                'answer_en' => 'Bought it online',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 1,
                'min_points' => 0,
                'next_question_ids' => '17',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 15,
                'answer_en' => 'You hired a designer',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 2,
                'min_points' => 0,
                'next_question_ids' => '18,19',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 16,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 16,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'We do not advise you to register the trademark in the current structure - go back and purchase a logo/mrk which you are able to have full access to and commercially benefit from use and register as a trademark.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 17,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 17,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'We do not advise you to register the trademark in the current structure - go back and purchase a logo/mrk which you are able to have full access to and commercially benefit from use and register as a trademark.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 18,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 18,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 19,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 19,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => 'We suggest reaching out to the designer and obtaining written confirmation that this is their work and they indemnify you for any copyright infringement.',
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 20,
                'answer_en' => 'Word',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 4,
                'min_points' => 0,
                'next_question_ids' => '21,22,23,24',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 20,
                'answer_en' => 'Combination',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 7,
                'min_points' => 0,
                'next_question_ids' => '25,26,27,28,29,30,31',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 20,
                'answer_en' => 'Logo',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 3,
                'min_points' => 0,
                'next_question_ids' => '32,33',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 20,
                'answer_en' => 'Image',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 4,
                'min_points' => 0,
                'next_question_ids' => '34,35,36,37',
                'is_final' => false,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 21,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 21,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 22,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 22,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 23,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 23,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 24,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 24,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 25,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 25,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 26,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 26,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 27,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 27,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 28,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 28,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 29,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 29,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 30,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 30,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 31,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 31,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 32,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 32,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 33,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 33,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 34,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 34,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 35,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 35,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 36,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 36,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 37,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 37,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 0,
                'min_points' => -2,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 38,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 1,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 38,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 1,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 39,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 1,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 39,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 1,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 40,
                'answer_en' => 'Yes',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 1,
                'min_points' => -1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
            [
                'question_id' => 40,
                'answer_en' => 'No',
                'answer_ar' => '',
                'answer_zh' => '',
                'answer_tr' => '',
                'max_points' => 1,
                'min_points' => 1,
                'next_question_ids' => null,
                'is_final' => true,
                'final_answer_message_en' => null,
                'final_answer_message_ar' => null,
                'final_answer_message_zh' => null,
                'final_answer_message_tr' => null
            ],
        ]);
        Schema::enableForeignKeyConstraints();
    }
}
